# print("How old are you?", end=' ')
# age = input()
# print("How tall are you?", end=' ')
# height = input()
# print("How much do you weigh?", end=' ')
# weight = input()
# print(f"So, you're {age} old, {height} tall and {weight} heavy.")
# #print("So, you're {} old, {} tall and {} heavy.".format(age, height, weight))

age=int(input("How old are you? "))
height = int(input("How tall are you?(for sm) "))
weight = int(input("How much do you weigh?(for kg) "))
print(f"So, you're {age} old, {height} tall and {weight} heavy.")